---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 28.10.2019 18:56
---

function wait_for_element(splash, css, max_wait)
  -- Wait until a selector matches an element
  -- in the page. Return an error if waited more
  -- than max_wait seconds.
  if max_wait == nil then
      max_wait = 10
  end
  return splash:wait_for_resume(string.format([[
    function main(splash) {
      var selector = '%s';
      var maxWait = %s;
      var end = Date.now() + maxWait*1000;



      function check() {
        if((...document.querySelectorAll(selector)).map( item => item.getAttribute('src') != '')) {
          splash.resume('Element found');
        } else if(Date.now() >= end) {
          var err = 'Timeout waiting for element';
          splash.error(err + " " + selector);
        } else {
          setTimeout(check, 200);
        }
      }
      check();
    }
  ]], css, max_wait))
end

function main(splash)
  splash:go(splash.args.url)
  wait_for_element(splash, splash.args.selector)
  return splash:html()
end